name: mt19937
description: Dart implementations of the Mersenne Twister pseudo-random number generator.
version: 0.1.0+1
repository: https://github.com/jamesderlin/dart_mt19937

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  fixnum: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  dartbag: ^0.3.0
  resource_importer: ^0.1.0
  test: ^1.16.0

resource_importer:
  destination: 'test/reference.resources.dart'
  resources:
    defaultSeedResults:
      path: reference/mt19937/default.txt
      type: List<String>
    maxSeedResults:
      path: reference/mt19937/max_seed.txt
      type: List<String>
    sequenceResults:
      path: reference/mt19937/sequence.txt
      type: List<String>
    defaultDoubleResults:
      path: reference/mt19937/double.txt
      type: List<String>
    defaultSeed64Results:
      path: reference/mt19937-64/default.txt
      type: List<String>
    maxSeed64Results:
      path: reference/mt19937-64/max_seed.txt
      type: List<String>
    sequence64Results:
      path: reference/mt19937-64/sequence.txt
      type: List<String>
    defaultDouble64Results:
      path: reference/mt19937-64/double.txt
      type: List<String>
