name: mt19937
description: Mersenne Twister implementations (MT19937 and MT19937-64).
version: 0.1.0
repository: https://github.com/jamesderlin/dart_mt19937

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  fixnum: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  test: ^1.16.0
